CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL,
    customer_id BIGINT,
    restaurant_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT fk_app_user_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_app_user_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)
);
CREATE INDEX idx_app_user_role ON app_user (role);
CREATE INDEX idx_app_user_customer ON app_user (customer_id);
CREATE INDEX idx_app_user_restaurant ON app_user (restaurant_id);

INSERT INTO app_user (email, password_hash, role, enabled, customer_id, restaurant_id, created_at, updated_at)
VALUES ('admin@bonusapp.local',
        '$2a$10$4SaqKn8FtHDvH2tVznaJ4OEEdcFiwCKyWoilOtse2OUPL8uZjcR72',
        'ADMIN',
        TRUE,
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

INSERT INTO app_user (email, password_hash, role, enabled, customer_id, restaurant_id, created_at, updated_at)
VALUES ('max.muster@example.com',
        '$2a$10$WyK9K4GPSu8ncnHDFeQkaOBkWp3cUhvzr/x.99t/2udSzs9M.dbV.',
        'CUSTOMER',
        TRUE,
        (SELECT id FROM customer WHERE email = 'max.muster@example.com'),
        (SELECT id FROM restaurant WHERE code = 'DEMO'),
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);
